language: node_js
node_js:
  - 12
before_script:
  - npm install @11ty/eleventy -g
script: npm run build --pathprefix="/beginnersBase11ty/"
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh_pages
